# Generated by Django 5.0 on 2024-01-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbackModels',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_feedback', models.TextField(max_length=900)),
                ('star_rating', models.IntegerField()),
                ('star_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sentment', models.TextField(max_length=20, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetails')),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
    ]
